### ISSUE TITLE
MMM-TAF not starting, undefined (reading 'fadeSpeed')

### ISSUE THREAD

**Issue by MajorC1983** [imperian/MMM-TAF#3]
Hi, after updating my MM to 2.18 MMM-TAF shows nothing and I get this error:

`MMM-TAF.js:247 Uncaught TypeError: Cannot read properties of undefined (reading 'fadeSpeed')`

**Comment by imperian** [comment]
I'm not able to reproduce, but I do see that I'm missing a default fadeSpeed.  I've updated the module.  Can you load and see if that worked?
